/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guimod1.guiclasses;

import com.mycompany.guimod1.businesslayer.ConnectionClass;
import com.mycompany.guimod1.businesslayer.paybill;
import com.mycompany.guimod1.system.SystemLayer;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author DELL
 */
public class billform extends javax.swing.JFrame {

    /**
     * Creates new form billform
     * 
     */
  
    private SystemLayer systemlayer;
    private paybill paybill;
    private int clientId;
    private int billID2;
    public billform() {
      
        initComponents();
        String[] columnNames = {"billID", "clientID", "amountDue", "dueDate"};
        DefaultTableModel tb1Model = new DefaultTableModel(columnNames, 0);
        billslist.setModel(tb1Model);
        paybill = new paybill();
        systemlayer = new SystemLayer(paybill);
    }
    public void setClientId(int clientId) {
        this.clientId = 1;
        System.out.println("clientId"+clientId);
         //loadBillInformation();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        billinfo2 = new javax.swing.JButton();
        billtable = new javax.swing.JScrollPane();
        billslist = new javax.swing.JTable();
        billinfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setEndColor(new java.awt.Color(86, 180, 211));
        kGradientPanel1.setStartColor(new java.awt.Color(52, 143, 80));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BILL INFORMATION");

        billinfo2.setText("SHOW BILL INFORMATION");
        billinfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billinfo2ActionPerformed(evt);
            }
        });

        billslist.setBackground(new java.awt.Color(51, 51, 51));
        billslist.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        billslist.setForeground(new java.awt.Color(255, 255, 255));
        billslist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BillID", "clientID", "Amountdue", "duedate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billslist.setGridColor(new java.awt.Color(102, 102, 102));
        billslist.setSelectionBackground(new java.awt.Color(0, 0, 0));
        billslist.setSelectionForeground(new java.awt.Color(255, 255, 255));
        billtable.setViewportView(billslist);

        billinfo.setText("PAY NOW!!!!");
        billinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(billinfo)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(billinfo2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(billtable, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billinfo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(billtable, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(billinfo)
                .addGap(32, 32, 32))
        );

        kGradientPanel1.add(jPanel2);
        jPanel2.setBounds(310, 160, 871, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1537, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billinfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billinfo2ActionPerformed
      // TODO add your handling code here:
        try {
            // Establish database connection
               ConnectionClass connection = new ConnectionClass();
       Connection connectionString=connection.getConnectionString();
String sql = "SELECT * FROM Bill WHERE clientID = ?";
        try (PreparedStatement preparedStatement = connectionString.prepareStatement(sql)) {
            // Set parameters in the prepared statement
            preparedStatement.setInt(1, 1);

            // Execute the query
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                // Clear existing data in the table model
                DefaultTableModel tb1Model = (DefaultTableModel) billslist.getModel();
                tb1Model.setRowCount(0);

                while (resultSet.next()) {
                    billID2 = resultSet.getInt("billID");
                    String billID = String.valueOf(resultSet.getInt("billID"));
                    String clientID = String.valueOf(resultSet.getInt("clientID"));
                    String amountDue = String.valueOf(resultSet.getInt("amountDue"));
                     Date dueDate = resultSet.getDate("dueDate");

                    String formattedDueDate = (dueDate != null) ? dueDate.toString() : "";
                    // Add data to the table model
                    String[] tbData = {billID, clientID, amountDue, formattedDueDate};
                    tb1Model.addRow(tbData);
                }
                
       

                // Close resources
            }
        }
      connectionString.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_billinfo2ActionPerformed

    private void billinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billinfoActionPerformed
         systemlayer.payingbill(billID2);
       
    }//GEN-LAST:event_billinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billinfo;
    private javax.swing.JButton billinfo2;
    private javax.swing.JTable billslist;
    private javax.swing.JScrollPane billtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

   
}
